Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> 
=============== RESTART: D:/网络163 姜圣玲/异常处理/test 2.py ===============
内容写入文件成功
>>> 
========== RESTART: D:/网络163 姜圣玲/异常处理/try test3 finally.py ==========
no such fiel

Error: 没有找到文件或读取文件失败
>>> 
========== RESTART: D:/网络163 姜圣玲/异常处理/try test3 finally.py ==========
no such fiel

Error: 没有找到文件或读取文件失败
>>> 
========== RESTART: D:/网络163 姜圣玲/异常处理/try test3 finally.py ==========
no such fiel
No such file or directory
Error: 没有找到文件或读取文件失败
>>> 
================= RESTART: D:/网络163 姜圣玲/异常处理/net.py =================
Bad hostname
>>> 
================ RESTART: D:/网络163 姜圣玲/异常处理/触发.py ================

Traceback (most recent call last):
  File "D:/网络163 姜圣玲/异常处理/触发.py", line 6, in <module>
    functionName(0)
  File "D:/网络163 姜圣玲/异常处理/触发.py", line 2, in functionName
    if level < 1:
NameError: global name 'level' is not defined
>>> 
================ RESTART: D:/网络163 姜圣玲/异常处理/触发.py ================

Traceback (most recent call last):
  File "D:/网络163 姜圣玲/异常处理/触发.py", line 6, in <module>
    functionName(2)
  File "D:/网络163 姜圣玲/异常处理/触发.py", line 2, in functionName
    if level < 1:
NameError: global name 'level' is not defined
>>> 
================ RESTART: D:/网络163 姜圣玲/异常处理/触发.py ================
Ok
else.....
finally always run.....
>>> 
